### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by SaeedZhiany**
Getting reactnative and android gradle plugin version from root project. this changes has been successfully built unlike my previous changes #78

### CODE REVIEW

**Comment by SaeedZhiany** [comment]
@avishayil 
I look at travis-ci build log and I saw that it build with gradle-4.10.2. I couldn't find where is the `gradle-wrapper.properties` file in this repository. It's possible the build is failed because of that. cause I test it in my project and everything is built successfully. also, I changed some other react-native libraries ([react-native-touch-id](https://github.com/naoufal/react-native-touch-id/pull/234), [react-native-svg](https://github.com/react-native-community/react-native-svg/pull/1038)) too and their builds are passed. can you check out yourself for double checking? thanks

**Comment by avishayil** [comment]
https://stackoverflow.com/questions/27031587/gradle-global-variable-not-in-scope-within-buildscript

I guess this is why it fails. You should define the `safeGetExt` function inside the `buildscript` scope as the gradle reads this block first.

**Comment by SaeedZhiany** [comment]
@avishayil 
but as I said I have changed your library's gradle file in my own project just like this PR (and other libraries I using) and the whole project building successfully.

**Comment by SaeedZhiany** [comment]
@avishayil 
Finally, I found the correct way for reading the property from the root project and as you can see, the build has been successfully done.
please check yourself again and merge it if possible. thanks

**Comment by SaeedZhiany** [comment]
@avishayil 
are you have plan release a new version containing this PR?

**Pull request merged**
