### PR TITLE
Update Podspeс due to issue #74

### PR DESCRIPTION
**Pull request by barzhomi**
Regarding issue #74 I've updated podspec and added `homepage` property to `package.json` for more friendly look of the library.

### CODE REVIEW

**Comment by barzhomi** [comment]
I may be wrong but looks like you have made a merge commit in my forked repository barzhomi/react-native-restart , but not accepted pull request and merged it to your original repository avishayil/react-native-restart.

**Comment by avishayil** [comment]
Hi @barzhomi I can see this commit, but how can I access your repository without making a pull request? it is supposed to be yours.
Can you create a new pull request?

**Comment by barzhomi** [comment]
Actually I also was surprised with that fact :) But this is default GitHub feature https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by avishayil** [comment]
@barzhomi Thanks for the reference, interesting!

**Pull request merged**
