### PR TITLE
fix(refactor): restart the app using the process phoenix

### PR DESCRIPTION
**Pull request by HammzaHM**

### CODE REVIEW

**Comment by todorone** [comment]
@avishayil This seems as much more reliable way to restart the app avoiding reported crashes and `setTimeout` workarounds. Could You please consider to merge it?

**Comment by avishayil** [comment]
Testing since Travis decided to stop working on PRs

**Comment by Nikola-Andreev** [comment]
@avishayil how did the testing go?

**Comment by todorone** [comment]
@avishayil If You worry about regression, at least "alpha"-ish release is highly appreciated. Thanks.

**Review by BogdanRad — APPROVED** [review]

**Comment by dan-trewin** [comment]
any update on a release for this?

**Comment by HammzaHM** [comment]
@todorone  I've made custom native module using this approach of restarting the app, and our app is live without any regressions

**Comment by dutradotdev** [comment]
+1
i need this fix!

**Review by dutradotdev — APPROVED** [review]

**Comment by dutradotdev** [comment]
@avishayil pls merge

**Comment by pedrocmello** [comment]
+1

**Review by pedrocmello — APPROVED** [review]

**Comment by dan-trewin** [comment]
@avishayil Whats the status on this? Plz merge. looks like it got approved.

**Comment by manny-cuboh** [comment]
@avishayil would also love this merged!

**Comment by avishayil** [comment]
Thanks @HammzaHM for this! looks great.

**Pull request merged**
