### PR TITLE
Added cocapods support

### PR DESCRIPTION
**Pull request by bilalsyed001**

### CODE REVIEW

**Comment by avishayil** [comment]
I'm not sure we need this, as we don't use any external framework to link.
What is this good for?

**Comment by bilalsyed001** [comment]
@avishayil  When integrating with existing apps or large projects RN framework comes with cocapods. What I tested manual linking doesn't work well.

Read more -> http://facebook.github.io/react-native/releases/0.49/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies

**Comment by avishayil** [comment]
OK, I'll test your configuration and decide. By the way, I updated the library today and tested automatic and manual linking, they all work well.

**Comment by avishayil** [comment]
I couldn't make it work with CocoaPods myself. Could you please add a working example project using this pod, let's say `ExampleWithPod` and adjust this PR? Also, instructions about how to get it working with CocoaPods would be necessary.
Thanks.

**Comment by avishayil** [comment]
Closing this due to inactivity. Please re-open if you think that's applicable. Thanks.

**Pull request closed without merging**
