### PR TITLE
implement C++ windows support

### PR DESCRIPTION
**Pull request by burtonrodman**
#145

### CODE REVIEW

**Comment by creambyemute** [comment]
@burtonrodman Cool! I have just today went the same route with `CoreApplication::Exit()` and `CoreApplication::RequestRestartAsync("")` for our Project and wanted to notfiy you but you already did it 👍 

Cheers!

**Comment by burtonrodman** [comment]
btw, I am by no means a C++ expert so please do feel free to provide any feedback on any aspect without fear of hurting my non-existent ego ;)

**Comment by creambyemute** [comment]
Me neither, I had my first C++/WinRT contact with RN-Windows.

From what I see, you handle errors better than I do. Our Restart is always triggered by an UI-Action so I ignored a big part of the FailureReason handling.
My implementation is as simple as:

```cpp
    winrt::fire_and_forget ExitHandler::restartApp(RN::ReactPromise<void> promise) noexcept
    try {
        co_await CoreApplication::RequestRestartAsync(winrt::to_hstring(""));
        promise.Resolve();
    } catch (const hresult_error& ex) {
        promise.Reject(RN::ReactError{ "Unable to restart app ", winrt::to_string(ex.message()).c_str() });
    }
```

**Comment by burtonrodman** [comment]
I see that the Travis CI PR build failed.  I'm assuming it does not support building C++/Windows.  How do you suggest we resolve this?

**Comment by abarcybr** [comment]
Hi @burtonrodman I think that the issue is with node v10 which is installed on the build slave. Can you please update the `nvm install` command to `nvm install 12`?

**Comment by avishayil** [comment]
Hi @burtonrodman I think that the issue is with node v10 which is installed on the build slave. Can you please update the nvm install command to nvm install 12?

**Comment by TheWirv** [comment]
Hey guys, I saw that the dependencies have been changed to hard ones (without any caret or tilde, or whatever). Is there anything in particular that prevents you from depending on `"react": "^17.0.1"` and `"react-native": "^0.64.1"` instead?

**Comment by avishayil** [comment]
> Hey guys, I saw that the dependencies have been changed to hard ones (without any caret or tilde, or whatever). Is there anything in particular that prevents you from depending on `"react": "^17.0.1"` and `"react-native": "^0.64.1"` instead?

Good catch. @burtonrodman can you please update the dependencies on `package.json` file and create a new yarn.lock? Also the relevant examples should be updated.

**Comment by burtonrodman** [comment]
@avishayil could you expound on what you mean by "the relevant examples"?

**Review by avishayil — APPROVED** [review]

**Comment by chrisglein** [comment]
FYI with this merged you probably want to update the React Native Directory to show that it works for Windows too:
https://reactnative.directory/?search=react-native-restart
https://github.com/react-native-community/directory#how-do-i-add-a-library

**Comment by avishayil** [comment]
Hi @burtonrodman any idea how can we test the Windows functionality using GitHub actions testing infrastructure?

**Pull request merged**
